### ISSUE TITLE
Convert SOWFA output into FAST input

### ISSUE THREAD

**Issue by enricogussoni** [NREL/SOWFA#42]
Hi all,

it is possible to convert the output from SOWFA (for example bladePointVmag or bladePointTorqueForce) to the input for a FAST case on the same turbine? I was thinking about convert the wind velocity computed by SOWFA into something that can be read by InflowWind.

**Comment by ewquon** [comment]
There are a couple of python utilities here: https://github.com/NWTC/datatools/tree/master/utilities
- structuredVTK_planes_to_hawc.py
- ensight_planes_to_hawc.py

Both depend on sampled data sets in OpenFOAM's "array" style. Structured VTK format is a custom SOWFA format whereas ensight is a native OpenFOAM format. The motivation for output in the hawc format is file I/O simplicity. This can be directly used as InflowWind input.

**Comment by ewquon** [comment]
One caveat: sampling in OpenFOAM (at least 2.4.x) occasionally fails at some locations. Because the structured VTK format defines the grid only in terms of an origin and grid spacing, if the sampling fails it will be unclear which points are missing (because coordinates for each point in the field are not explicitly saved). The upside to using structured VTK is that you're not saving the full mesh at every time step, and you can easily visualize the results in Paraview without any additional effort.
